name: Rust

on:
    push:
        tags:
            - release-*
env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: show
                run: |
                    rustc --version
                    cargo --version
