name: Rust

on:
    push:
        branches:
            -   main
env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: show
                run: |
                    rustc --version
                    cargo --version

            -   name: cargo build
                run: |
                    cargo build --release
                    ls -al target/release

#            -   name: Uploading assets...
#                if: ${{ !env.ACT }}
#                id: upload-release-asset
#                uses: actions/upload-release-asset@v1
#                env:
#                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#                with:
#                    upload_url: ${{ github.event.release.upload_url }}
#                    asset_path: ./kubectl-karmada-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
#                    asset_name: kubectl-karmada-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
#                    asset_content_type: application/gzip




#            -   name: Build
#                run: |
#                    cargo build --release
#                    ls -al
