name: Rust

on:
    push:
        branches:
            -   main
env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    rust-version: 1.55.0
            -   name: show
                run: |
                    rustc --version
                    cargo --version

#            -   name: Build
#                run: |
#                    cargo build --release
#                    ls -al
