name: Rust

on:
    push:
        tags:
            - "v*"

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Generate App Version
                run: |
                    echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
                    echo $GITHUB_ENV
                    pwd

            -   name: cargo build
                run: |
                    pwd
                    cargo build --release
                    ls -al target/release/fake-redis
                    zip fake-redis.zip target/release/fake-redis

            # 创建release
            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
                with:
                    tag_name: ${{ env.APP_VERSION }}
                    release_name: ${{ env.APP_VERSION }}
                    draft: false
                    prerelease: false


#            # 上传文件到 release
            -   name: Upload Binary File To Release
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: fake-redis.zip
                    asset_name: fake-redis.zip
                    asset_content_type: application/zip
